---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef_intro::default]
    data_bags_path: 'test/integration/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/data_bags/testsecret'
    attributes:
      chef_intro:
        username: neo