name 'chef_intro'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_intro'
long_description 'Installs/Configures chef_intro'
version '0.1.0'
